"""empty message

Revision ID: 0736908305ec
Revises: 6aadf6de4f9d
Create Date: 2026-04-10 17:11:13.511088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0736908305ec'
down_revision = '6aadf6de4f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_usuario', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('tipo_usuario')

    # ### end Alembic commands ###
