"""empty message

Revision ID: 12255b4422cf
Revises: 7b13dfd83f2b
Create Date: 2026-04-14 12:00:57.888554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12255b4422cf'
down_revision = '7b13dfd83f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_aulas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.drop_column('quantidade_aulas')

    # ### end Alembic commands ###
