"""empty message

Revision ID: 38af1f9fdb9d
Revises: f56595fdb460
Create Date: 2026-04-13 15:15:22.676045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38af1f9fdb9d'
down_revision = 'f56595fdb460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciclos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'escola_id', 'usuario_id', name='_ciclo_escola_uc')
    )
    with op.batch_alter_table('ciclos', schema=None) as batch_op:
        batch_op.create_index('idx_ciclo_escola', ['escola_id'], unique=False)

    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.create_index('idx_aula_escola_dia', ['escola_id', 'dia_aula'], unique=False)
        batch_op.create_index('idx_aula_usuario_dia', ['usuario_id', 'dia_aula'], unique=False)

    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.create_index('idx_disciplina_usuario', ['usuario_id'], unique=False)

    with op.batch_alter_table('escolas', schema=None) as batch_op:
        batch_op.create_index('idx_escola_cidade', ['cidade'], unique=False)
        batch_op.create_index('idx_escola_usuario', ['usuario_id'], unique=False)

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciclo_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('_serie_escola_uc'), type_='unique')
        batch_op.create_unique_constraint('_nome_ciclo_escola_uc', ['nome', 'ciclo_id', 'escola_id'])
        batch_op.create_index('idx_serie_ciclo', ['ciclo_id'], unique=False)
        batch_op.create_index('idx_serie_escola', ['escola_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('series_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ciclos', ['ciclo_id'], ['id'])
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('series_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_index('idx_serie_escola')
        batch_op.drop_index('idx_serie_ciclo')
        batch_op.drop_constraint('_nome_ciclo_escola_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_serie_escola_uc'), ['nome', 'escola_id', 'usuario_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('ciclo_id')

    with op.batch_alter_table('escolas', schema=None) as batch_op:
        batch_op.drop_index('idx_escola_usuario')
        batch_op.drop_index('idx_escola_cidade')

    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.drop_index('idx_disciplina_usuario')

    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.drop_index('idx_aula_usuario_dia')
        batch_op.drop_index('idx_aula_escola_dia')

    with op.batch_alter_table('ciclos', schema=None) as batch_op:
        batch_op.drop_index('idx_ciclo_escola')

    op.drop_table('ciclos')
    # ### end Alembic commands ###
