"""adicionado o campo criado_em na tabela escola

Revision ID: b56c1d269bf7
Revises: c8af00333b87
Create Date: 2026-04-11 15:23:48.565665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56c1d269bf7'
down_revision = 'c8af00333b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escolas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escolas', schema=None) as batch_op:
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###
